import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import "./home.css";
import "../styles/header.css";
import "../styles/login.css";
import "../styles/signup.css";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider telemetry={false}>
      <html lang="en">
        <body>
          <Header />
          <div id="root">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}

