import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { cookies } from "next/headers";
import "./globals.css";
import "./home.css";
import "../styles/header.css";
import "../styles/login.css";
import "../styles/signup.css";
import Header from "../components/Header";
import { DevModeProvider } from "./providers/DevModeProvider";
import { CameraResultsProvider } from "./providers/CameraResultsProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const dev = cookieStore.get("dev")?.value === "true";

  return (
    <ClerkProvider telemetry={false}>
      <html lang="en">
        <body>
          <DevModeProvider initial={dev}>
            <CameraResultsProvider>
              <Header />
              <div id="root">{children}</div>
            </CameraResultsProvider>
          </DevModeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

